apiVersion: apps/v1
kind: Deployment
metadata:
  name: "deployment0"
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "app-deployment0"
  template:
    metadata:
      labels:
        app: "app-deployment0"
    spec:
      containers:
      - name: "devconnect"
        image: "me-west1-docker.pkg.dev/eco-tract-407114/shira-repo/django-app:v0.0.0"