apiVersion: v1
kind: Service
metadata:
  name: service0
  namespace: production
spec:
  selector:
    app: "app-deployment0"
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
  type: LoadBalancer