apiVersion: v1
kind: Service
metadata:
  name: service
  namespace: production
spec:
  selector:
    app: "app-deployment"
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
  type: LoadBalancer